services:

  # 1. Nginx Web Server
  bdn_karanganyar_web:
    image: nginx:alpine
    container_name: bdn_karanganyar_web
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - bdn_karanganyar_app
    restart: unless-stopped
    networks:
      - bdn_karanganyar_network


  # 2. Laravel Application (PHP-FPM)
  bdn_karanganyar_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bdn_karanganyar_app
    volumes:
      - .:/var/www/html
    depends_on:
      - bdn_karanganyar_db
    restart: unless-stopped
    networks:
      - bdn_karanganyar_network
    environment:
      APP_ENV: local
      APP_DEBUG: "false"

      DB_CONNECTION: mysql
      DB_HOST: bdn_karanganyar_db
      DB_PORT: 3306
      DB_DATABASE: bdn_karanganyar_db
      DB_USERNAME: root
      DB_PASSWORD: root


  # 3. MySQL Database
  bdn_karanganyar_db:
    image: mysql:8.0
    container_name: bdn_karanganyar_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bdn_karanganyar_db
    ports:
      - "3306:3306"
    volumes:
      - bdn_karanganyar_db_data:/var/lib/mysql
    networks:
      - bdn_karanganyar_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 30s
      timeout: 10s
      retries: 5


networks:
  bdn_karanganyar_network:
    driver: bridge


volumes:
  bdn_karanganyar_db_data: